# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: WeekiXu

user:
  name: WeekiXu
  avatar: /images/avatar.jpg
  location: In the dust
  description: May the Force be with you

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: WeekiXu/blog # your blog repo

# auto
# dark
# light
# user-can-set
appearance: dark # Default value is auto
